fail_fast: false
default_language_version:
  python: python3
default_stages:
- commit
- push
minimum_pre_commit_version: 3.0.0
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
  - id: nbqa-pyupgrade
    args: [--py38-plus]
  - id: nbqa-black
  - id: nbqa-isort
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
