fail_fast: false
default_language_version:
  python: python3
default_stages:
- commit
- push
minimum_pre_commit_version: 3.0.0
repos:
- repo: https://github.com/tomcatling/black-nb
  rev: '0.7'
  hooks:
  - id: black-nb
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
