language: python

python: "3.6"

os: linux

dist: bionic  # Ubuntu 18.04

env:
  global:
    secure: "nsXrAR+koQ5SQyJk+GCsLM4t7tGpaMU/fMXkrm2ms6CT0vyNDOD91MTJcPEHlORdduDfc0SuguYMVftn6m8hJVhd/H8OIOmuioapxafEEy1GbVAT8lozkditTf9QoHC8d6o7DMCHWrp62H1T8GMRjS8+a+PN8bajrpjWkawjd59tbQ04I0gOGDI7qHalwQTILgCbmOitqMYATn3I1t3Id9Prfwrssxve7vpfxnmDIfJB8S6sP8nweaf0CwvEAC+kbGx2VIeGGZxXKxaJMws9WkoVbwrM7kR4LQAtPrKTRaHJz2f1ZOGxRiIeNOm2tk5ezviA1PHe3g5VoFD/bsd6csezZmS+pCMhR1ip7tu6oEAW5O0zBd9zG8tZ5eI0IUUeYF6v2hlqBykuXjiVzCGP3eLLwS+SYYagN+H2kXeNafwS29iLKpAoX8DnYb6InGPcZalN1wyYgpbWrmbu47O36Lf4jrkKwK4N4DT54VWWcSO2bsr4G7GvXls3B+pD2jLlY7TvS53icm7zBb4uSl5rj54nuVQ/eLiY2QFIfRwQbGHBSgCyAfuEm2rntkLgco2FtrgrXNCAstEDkpjZApaNi/gwwEKFKolNoi8AERahSXpvWs3Bt1mjs/6wQgA+3f0UTmhQvoMckvhBG0bdUQJxDlWraghiE8Mm7SO8mzl97+4="

before_install:
  - "export R_VERSION=`R --version | head -n 1 | cut -d' ' -f3-4`"
  - echo "Running R $R_VERSION"
  - pip install -r requirements.txt
  - python -m ipykernel install --name cellrank --user
addons:
  apt:
    update: true
  sources:
    - sourceline: "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/"
      key_url: "http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xE298A3A825C0D65DFD57CBB651716619E084DAB9"
  packages:
    - libopenblas-base
    - r-base
    - r-base-dev
    - r-cran-mgcv

install:
  - git clone https://github.com/theislab/cellrank
  - cd cellrank
  - pip install -e .[test]
  - python-vendorize
  - cd ..

script:
  - travis_wait 30 pytest

after_success:
  - curl -X POST -d "branches=master" -d "token=$RTD_TOKEN" https://readthedocs.org/api/v2/webhook/cellrank/125510/
