language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

os: linux

cache:
  - pip
  - apt

env:
  - USE_SLEPC=true
  - USE_SLEPC=false

jobs:
  include:
    - name: "Notebooks and documentation regen and deployment"
      os: linux
      python: "3.8"
      env:
        - USE_SLEPC=true
        # RTD and CR_NOTEBOOKS tokens, respectively
        - secure: "nsXrAR+koQ5SQyJk+GCsLM4t7tGpaMU/fMXkrm2ms6CT0vyNDOD91MTJcPEHlORdduDfc0SuguYMVftn6m8hJVhd/H8OIOmuioapxafEEy1GbVAT8lozkditTf9QoHC8d6o7DMCHWrp62H1T8GMRjS8+a+PN8bajrpjWkawjd59tbQ04I0gOGDI7qHalwQTILgCbmOitqMYATn3I1t3Id9Prfwrssxve7vpfxnmDIfJB8S6sP8nweaf0CwvEAC+kbGx2VIeGGZxXKxaJMws9WkoVbwrM7kR4LQAtPrKTRaHJz2f1ZOGxRiIeNOm2tk5ezviA1PHe3g5VoFD/bsd6csezZmS+pCMhR1ip7tu6oEAW5O0zBd9zG8tZ5eI0IUUeYF6v2hlqBykuXjiVzCGP3eLLwS+SYYagN+H2kXeNafwS29iLKpAoX8DnYb6InGPcZalN1wyYgpbWrmbu47O36Lf4jrkKwK4N4DT54VWWcSO2bsr4G7GvXls3B+pD2jLlY7TvS53icm7zBb4uSl5rj54nuVQ/eLiY2QFIfRwQbGHBSgCyAfuEm2rntkLgco2FtrgrXNCAstEDkpjZApaNi/gwwEKFKolNoi8AERahSXpvWs3Bt1mjs/6wQgA+3f0UTmhQvoMckvhBG0bdUQJxDlWraghiE8Mm7SO8mzl97+4="
        - secure: "DpoCDfamJBfYhzTuH7w1hBbKp7BeVZWYNXKWsDoFEbuinLCL2P8a7dvNVfbiBqWqnHRK3f8sjIisBy+hqMM++taoAV9f6t33ScYYp+Sl9uEaVW7O7m2kwG/oYz60j8loEqFrh0iHMuy1L+cJlDu5QvjJ6XSerppmU2ScdAmj8BNd/7KmpBZQqYY+6ktruEFXvvFowPn2J+VS8g+azcqwo7AIODPSscBB/wcnqdTnTgrlR+PCbas4OcZG5SNYJ4UJMsN/j4YC2P3vOtoIewKq5DePxnpRN4IBAKLXMJSI0AADeCSUWXus4mhsGsMm8GPbgI+cX3dn5sUGrqmVsa8eXwakpcqBbPSkcBSkNhRp0PZY9I38rOTbEnlPWcL4VJzV0t6e+cWVt1An4dmZEtUjGS2ddCoGr3C0x3A1f3Ly0rU+H6o16sEl2jc8QpGWClI/8t/hwveUVyyKO372NHbfIjLG/qO9q8sfCUMYm2HKleUZViP/a7xDUmS5gu/sCk4Okgi5TDx9EJN8r8jA5QOm4VOH7J9xWtxVGxyVTteoScQaq+e/1Xi5Jsi4jnLII3PRqtoI4hCirAAa/yVGBEASsrLe2k4pUcZGJKiBldi1WO/36uI0EMsxaZb8qN47QPItphCKbnI5K9FO41DetJrfxybcZLYJF1vSa72Yf/4XW3I="

stages:
  - name: after_success
    if: type = push && branch = master && env(CR_NOTEBOOKS) IS present && env(RTD_TOKEN) IS present

before_install:
  - ./.scripts/ci/before_install.sh || travis_terminate 1

install:
  - ./.scripts/ci/install.sh || travis_terminate 1

script:
  - travis_wait 30 ./.scripts/ci/test.sh

after_success:
  - ./.scripts/ci/deploy.sh

notifications:
  email:
    recipients:
      - info@cellrank.org
    on_success: never
    on_failure: always
