name: cellrank
channels:
-   conda-forge
dependencies:
-   python=3.8
-   pip
-   notebook
-   python-igraph
-   pip:
    -   cellrank>=1.4.0
    -   louvain>=0.6,!=0.6.2
    -   git+https://github.com/broadinstitute/wot@master
