name: cellrank2
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter
  - python-igraph
  - matplotlib>=3.2.1
  - pip:
    - git+https://github.com/theislab/cellrank
    - scvelo>=0.2.0
    - anndata>=0.7.1
    - louvain>=0.6,!=0.6.2
