name: cellrank
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - notebook
  - python-igraph
  - pip:
    - cellrank>=1.0.0rc6
    - scvelo>=0.2.0
    - anndata>=0.7.1
    - louvain>=0.6,!=0.6.2
