[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
include_trailing_comma = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "NUMERIC", "BIO", "PLOTTING", "FIRSTPARTY", "LOCALFOLDER"]
known_numeric = ["numpy", "scipy", "pandas", "sklearn"]
known_bio = ["anndata", "scanpy", "scvelo", "cellrank"]
known_plotting = ["IPython", "matplotlib", "seaborn"]
