name: CI

on:
    repository_dispatch:
        types: [rebuild]
    push:
        branches: [main, tutorial/*, fix/*]
        paths: [tutorials/*.ipynb, tests/*.py, requirements.txt, environment.yml]
    pull_request:
        branches: [main]
        paths: [tutorials/*.ipynb, tests/*.py, requirements.txt, environment.yml]

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
        -   uses: actions/checkout@v2
            with:
                path: cellrank_notebooks
        -   name: Checkout CellRank
            uses: actions/checkout@v2
            with:
                repository: theislab/cellrank
                ref: main
                path: cellrank

        -   name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8

        -   name: Get pip cache dir
            id: pip-cache
            run: |
                echo "::set-output name=dir::$(pip cache dir)"

        -   name: Cache pip
            uses: actions/cache@v2
            with:
                path: |
                    ${{ steps.pip-cache.outputs.dir }}
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

        -   name: Install pip dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python -m ipykernel install --name cellrank --user  # to run the notebook engine
            working-directory: ./cellrank_notebooks

        -   name: Install CellRank
            # test also installs python-igraph and leidenalg
            run: |
                pip install -e'.[test]'
            working-directory: ./cellrank

        -   name: Test
            run: |
                python -m pytest --regenerate
                git status
            working-directory: ./cellrank_notebooks

        -   name: Commit changes
            if: ((github.event_name == 'repository_dispatch' && github.event.action == 'rebuild') || github.event_name == 'push') && github.ref == 'refs/heads/main'
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                repository: cellrank_notebooks
                commit_message: '[auto][ci skip] Regenerate tutorials'
                file_pattern: tutorials/*.ipynb
                commit_user_name: CI
                skip_dirty_check: false

        -   name: Request documentation rebuild
            if: steps.auto-commit-action.outputs.changes_detected == 'true'
            run: |
                curl -X POST -d "branches=main" -d "token=${{ secrets.RTD_TOKEN }}" "${{ secrets.RTD_WEBHOOK }}"
